version: "3"
services:
  keycloak:
    image: jboss/keycloak:10.0.1
    volumes:
      - ./src/main/resources/keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/currency-realm.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8081:8080
